### ISSUE TITLE
External HomeAssistant instance

### ISSUE THREAD

**Issue by sakalauskas** [dcmartin/motion-ai#19]
I already run HASS.io on Raspberry Pi 4. I do have Jetson Nano, where I'd like to install motion-ai and connect it to the HASS.io on Raspberry Pi.

Looking at the installation instructions, it looks like another home-assistant instance needs to be installed (locally) for motion-ai.

Can it be set up with a single home assistant instance?

**Comment by dcmartin** [comment]
Nope.  You can share the same MQTT broker between the two instances and then you can pick up the same MQTT topics.
