### ISSUE TITLE
does the quickstart require a pre installed home assistant ?

### ISSUE THREAD

**Issue by githubnoobjk** [dcmartin/motion-ai#20]
does the quickstart require a pre installed home assistant ?
Or will the quickstart install home-assistant

I followed the instruction on facebook , but get some errors there (johan kruize)

**Comment by dcmartin** [comment]
The QS does everything after installation of LINUX; works on Ubuntu18, Rasbian Buster, and Debian10.

If you have errors when following the documentation (https://github.com/dcmartin/motion-ai/blob/master/docs/QUICKSTART.md), please LMK.
